<!-- IF "DELETE PRODUCT" -->
<!-- storage -->
DELETE PRODUCT IMAGE
DELETE PRODUCT CATALOG
DELETE SERIES IMAGE
DELETE SERIES CATALOG
DELETE SPEC IMAGE
DELETE SPEC CATALOG
<!-- database -->
DELETE SPEC VALUE
DELETE SPEC
DELETE SERIES
DELETE PRODUCT

<!-- IF "DELETE SERIES" -->
<!-- storage -->
DELETE SERIES IMAGE
DELETE SERIES CATALOG
DELETE SPEC IMAGE
DELETE SPEC CATALOG
<!-- database -->
DELETE SPEC VALUE
DELETE SPEC
DELETE SERIES

<!-- IF "DELETE SPEC" -->
<!-- storage -->
DELETE SPEC IMAGE
DELETE SPEC CATALOG
<!-- database -->
DELETE SPEC VALUE
DELETE SPEC

<!-- IF "MASTER SPEC" -->
<!-- database -->
DELETE SPEC VALUE
DELETE MASTER SPEC
